spring:
  application:
    name: demo
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: whduddlek123!
  sql:
    init:
      schema-locations: classpath:schema.sql
      platform: mysql
      mode: always
logging:
  level:
    org:
      springframework:
        r2dbc: debug